[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
healthcheckInterval = 30
restartPolicyType = "on_failure"